import "./globals.css";
import { Inter } from "next/font/google";

const fonts = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Hotels",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={fonts.className}>{children}</body>
    </html>
  );
}
